# Generated by Django 3.2.9 on 2021-12-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=9, unique=True)),
                ('brand', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('oil_type', models.CharField(choices=[('A-95', 'A-95'), ('DT', 'DT')], max_length=7)),
            ],
            options={
                'db_table': 'auto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('pickup_adress', models.CharField(max_length=45)),
                ('delivery_adress', models.CharField(max_length=45)),
                ('weight', models.IntegerField()),
                ('type', models.CharField(choices=[('TENT', 'TENT'), ('CONTAINER', 'CONTAINER'), ('REFRIGERATOR', 'REFRIGERATOR')], max_length=30)),
                ('cargo_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('adress', models.CharField(max_length=45)),
                ('contract', models.CharField(max_length=9, unique=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=45)),
                ('s_name', models.CharField(max_length=45)),
                ('phone', models.IntegerField(unique=True)),
                ('hiring_date', models.DateField()),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id_mechanic', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=45)),
                ('s_name', models.CharField(max_length=45)),
                ('phone', models.IntegerField(unique=True)),
                ('hiring_date', models.DateField()),
            ],
            options={
                'db_table': 'mechanic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_storage', models.AutoField(primary_key=True, serialize=False)),
                ('storage_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportManager',
            fields=[
                ('id_emploee', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=45)),
                ('s_name', models.CharField(max_length=45)),
                ('phone', models.IntegerField(unique=True)),
                ('hiring_date', models.DateField()),
            ],
            options={
                'db_table': 'support_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id_trailer', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=9, unique=True)),
                ('brand', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('volume', models.IntegerField()),
            ],
            options={
                'db_table': 'trailer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id_place', models.AutoField(primary_key=True, serialize=False)),
                ('place_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
    ]
